### ISSUE TITLE
TypeError: transport is not a constructor

### ISSUE THREAD

**Issue by petr24** [avens19/winston-sumologic-transport#1]
Hey I am trying to use this with a Meteor app, I have added the packages.
However when the app starts I am getting a Type Error. 

Any ideas as to what could be happening.

Code below. 

```
    var winston = require("winston");
    require("winston-sumologic-transport").SumoLogic;
    
    var sumoLogicSettings = {
        url: "url string here",
        level: Meteor.settings.public.logLevel,
        silent: false
    };
    
    winston.add(winston.transports.SumoLogic, sumoLogicSettings);
```

And the error output

```

W20180117-13:42:22.661(-8)? (STDERR) /.meteor/packages/meteor-tool/.1.6.0_1.vdt2kg++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20180117-13:42:22.662(-8)? (STDERR) 						throw(ex);
W20180117-13:42:22.662(-8)? (STDERR) 						^
W20180117-13:42:22.662(-8)? (STDERR) 
W20180117-13:42:22.663(-8)? (STDERR) TypeError: transport is not a constructor
W20180117-13:42:22.663(-8)? (STDERR)     at exports.Logger.Logger.add (/node_modules/winston/lib/winston/logger.js:481:41)
W20180117-13:42:22.663(-8)? (STDERR)     at Object.winston.(anonymous function) [as add] (/node_modules/winston/lib/winston.js:86:34)
W20180117-13:42:22.663(-8)? (STDERR)     at GlobalDec-Lib.js (lib/helpers/GlobalDec-Lib.js:18:13)
W20180117-13:42:22.663(-8)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:343:9)
W20180117-13:42:22.663(-8)? (STDERR)     at require (packages/modules-runtime.js:238:16)
W20180117-13:42:22.663(-8)? (STDERR)     at /.meteor/local/build/programs/server/app/app.js:11181:1
W20180117-13:42:22.664(-8)? (STDERR)     at infos.forEach.info (/.meteor/local/build/programs/server/boot.js:414:13)
W20180117-13:42:22.664(-8)? (STDERR)     at Array.forEach (<anonymous>)
W20180117-13:42:22.664(-8)? (STDERR)     at /.meteor/local/build/programs/server/boot.js:413:9
W20180117-13:42:22.664(-8)? (STDERR)     at /.meteor/local/build/programs/server/boot.js:463:5
W20180117-13:42:22.664(-8)? (STDERR)     at Function.run (/carbon/.meteor/local/build/programs/server/profile.js:510:12)
W20180117-13:42:22.664(-8)? (STDERR)     at /.meteor/local/build/programs/server/boot.js:462:11
=> Exited with code: 1
```

**Comment by avens19** [comment]
Hey! Sorry for missing this. Apparently my usage instructions suck but I've updated them and added some new features to the code. You can now upgrade to version 2.0.0
